name: skadi
channels:
- conda-forge
- bioconda
dependencies:
- python=3.11
- aria2
- csvtk
- seqkit
- bbmap
- taxopy
- rapidfuzz
- taxonkit=0.18.0
- mmseqs2 [version='>=17.b804f']
- snakemake
- pyfastx
- click
- tqdm
- biopython
- openpyxl
- pyyaml
- pandas
- numpy
- polars
- pip
- prodigal-gv
- blast
- diamond>=2.1.14
